# Read more here: https://github.com/jusx/mergeable#configuration
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: approvals
        min:
          count: 2
      - do: assignee
        min:  
          count: 1
      - do: description
        no_empty:
           enabled: true
        must_exclude:
           regex: 'DO NOT MERGE|WIP'
      - do: title
        no_empty:
           enabled: true
        must_exclude:
           regex: 'DO NOT MERGE|WIP'
